-- ============================================================================
-- Hospital Snowflake Demo - Environment Setup
-- ============================================================================
-- This script sets up the database, schema, and roles for the hospital demo
-- IMPORTANT: Run this script as ACCOUNTADMIN for warehouse creation privileges

-- 0. Change role
USE ROLE accountadmin;

-- 1. Create Database and Schema
CREATE OR REPLACE DATABASE HOSPITAL_DEMO
COMMENT = 'Database for hospital clinical team Snowflake demonstration';

USE DATABASE HOSPITAL_DEMO;

CREATE OR REPLACE SCHEMA RAW_DATA
COMMENT = 'Schema for raw data loaded from S3';

CREATE OR REPLACE SCHEMA TRANSFORMED
COMMENT = 'Schema for transformed dimensional model';

CREATE OR REPLACE SCHEMA ANALYTICS
COMMENT = 'Schema for analytics and reporting views';

-- 2. Create Roles for RBAC Demo
USE ROLE ACCOUNTADMIN;

-- Clinical Roles
CREATE OR REPLACE ROLE CLINICAL_ADMIN
COMMENT = 'Full access for clinical administrators';

CREATE OR REPLACE ROLE PHYSICIAN
COMMENT = 'Access for attending physicians';

CREATE OR REPLACE ROLE NURSE
COMMENT = 'Limited access for nursing staff';

CREATE OR REPLACE ROLE ANALYST
COMMENT = 'Analytics access for hospital analysts';

CREATE OR REPLACE ROLE DATA_ENGINEER
COMMENT = 'Data engineering and ETL access';

-- 3. Grant Role Hierarchy
GRANT ROLE CLINICAL_ADMIN TO ROLE SYSADMIN;
GRANT ROLE DATA_ENGINEER TO ROLE SYSADMIN;
GRANT ROLE ANALYST TO ROLE CLINICAL_ADMIN;
GRANT ROLE PHYSICIAN TO ROLE CLINICAL_ADMIN;
GRANT ROLE NURSE TO ROLE PHYSICIAN;

-- 4. Database Permissions
GRANT USAGE ON DATABASE HOSPITAL_DEMO TO ROLE CLINICAL_ADMIN;
GRANT USAGE ON DATABASE HOSPITAL_DEMO TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE HOSPITAL_DEMO TO ROLE ANALYST;
GRANT USAGE ON DATABASE HOSPITAL_DEMO TO ROLE PHYSICIAN;
GRANT USAGE ON DATABASE HOSPITAL_DEMO TO ROLE NURSE;

-- Schema Permissions
GRANT ALL ON SCHEMA RAW_DATA TO ROLE DATA_ENGINEER;
GRANT ALL ON SCHEMA TRANSFORMED TO ROLE DATA_ENGINEER;
GRANT ALL ON SCHEMA ANALYTICS TO ROLE DATA_ENGINEER;

GRANT USAGE ON SCHEMA RAW_DATA TO ROLE CLINICAL_ADMIN;
GRANT USAGE ON SCHEMA TRANSFORMED TO ROLE CLINICAL_ADMIN;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE CLINICAL_ADMIN;

GRANT USAGE ON SCHEMA TRANSFORMED TO ROLE ANALYST;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE ANALYST;

GRANT USAGE ON SCHEMA ANALYTICS TO ROLE PHYSICIAN;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE NURSE;

-- 5. Create Warehouses for Different Workloads
-- Note: Warehouse creation requires ACCOUNTADMIN privileges
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE HOSPITAL_LOAD_WH
WITH 
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 3
    SCALING_POLICY = 'STANDARD'
COMMENT = 'Warehouse for data loading operations';

CREATE OR REPLACE WAREHOUSE HOSPITAL_ANALYTICS_WH
WITH 
    WAREHOUSE_SIZE = 'LARGE'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 5
    SCALING_POLICY = 'STANDARD'
COMMENT = 'Warehouse for analytics and reporting';

CREATE OR REPLACE WAREHOUSE HOSPITAL_ADHOC_WH
WITH 
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 2
    SCALING_POLICY = 'ECONOMY'
COMMENT = 'Warehouse for ad-hoc queries and exploration';

-- 6. Warehouse Permissions
GRANT USAGE ON WAREHOUSE HOSPITAL_LOAD_WH TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE HOSPITAL_ANALYTICS_WH TO ROLE CLINICAL_ADMIN;
GRANT USAGE ON WAREHOUSE HOSPITAL_ANALYTICS_WH TO ROLE ANALYST;
GRANT USAGE ON WAREHOUSE HOSPITAL_ADHOC_WH TO ROLE PHYSICIAN;
GRANT USAGE ON WAREHOUSE HOSPITAL_ADHOC_WH TO ROLE NURSE;

-- 7. Resource Monitors for Cost Control
CREATE OR REPLACE RESOURCE MONITOR HOSPITAL_MONTHLY_LIMIT
WITH 
    CREDIT_QUOTA = 1000
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS 
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO SUSPEND
        ON 100 PERCENT DO SUSPEND_IMMEDIATE;

-- Apply monitor to warehouses
ALTER WAREHOUSE HOSPITAL_LOAD_WH SET RESOURCE_MONITOR = HOSPITAL_MONTHLY_LIMIT;
ALTER WAREHOUSE HOSPITAL_ANALYTICS_WH SET RESOURCE_MONITOR = HOSPITAL_MONTHLY_LIMIT;
ALTER WAREHOUSE HOSPITAL_ADHOC_WH SET RESOURCE_MONITOR = HOSPITAL_MONTHLY_LIMIT;

-- 8. Show Setup Results
SHOW DATABASES LIKE 'HOSPITAL_DEMO';
SHOW SCHEMAS IN DATABASE HOSPITAL_DEMO;
SHOW ROLES LIKE 'CLINICAL_%';
SHOW ROLES LIKE 'PHYSICIAN';
SHOW ROLES LIKE 'NURSE';
SHOW ROLES LIKE 'ANALYST';
SHOW ROLES LIKE 'DATA_ENGINEER';
SHOW WAREHOUSES LIKE 'HOSPITAL_%';

-- 9. Set Context for Next Steps
USE ROLE DATA_ENGINEER;
USE DATABASE HOSPITAL_DEMO;
USE SCHEMA RAW_DATA;
USE WAREHOUSE HOSPITAL_LOAD_WH;
